version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
      - ./docker_db_share:/root/docker_db_share
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
      - ./static:/static
    depends_on:
      - db
    tty: true # 常時起動用設定
